export default {
  LOCALE_CHANGE: 'LOCALE_CHANGE',
  LOCALE_UPDATED: 'LOCALE_UPDATED',
  
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  REMOVE_TOKEN: 'REMOVE_TOKEN',

  ADD_USERNAME: 'ADD_USERNAME',

  ITEMS_REQUEST: 'ITEMS_REQUEST',
  ITEMS_SUCCESS: 'ITEMS_SUCCESS',
  ITEMS_FAILURE: 'ITEMS_FAILURE',
  REMOVE_ITEMS: 'REMOVE_ITEMS',

  ADD_ITEMS_LOADING: 'ADD_ITEMS_LOADING',
  ADD_ITEMS_FAILURE: 'ADD_ITEMS_FAILURE',

  
  ITEM_REQUEST: 'ITEM_REQUEST',
  ITEM_SUCCESS: 'ITEM_SUCCESS',
  ITEM_FAILURE: 'ITEM_FAILURE',
  ITEM_DETAILS: 'ITEM_DETAILS',

  ADD_ITEMS_SUCCESS:'ADD_ITEMS_SUCCESS',

  ADD_STATES_REQUEST: 'ADD_STATES_REQUEST',
  ADD_STATES_SUCCESS:'ADD_STATES_SUCCESS',
  ADD_STATES_FAILURE: 'ADD_STATES_FAILURE',
  REDUCE_ITEMS_STATES: 'REDUCE_ITEMS_STATES',

  CHANGE_STATES_FILTER: 'CHANGE_FILTER',
  SET_LOADING: 'SET_LOADING',
  SET_FINISHED_LOADING: 'SET_FINISHED_LOADING',

  CHANGE_PAGE: 'CHANGE_PAGE',

  CHANGE_SEARCH_FILTER: 'CHANGE_SEARCH',
};